### PR TITLE
Ui improvements. Trying using a headerbar. Need to test how it looks …

### PR DESCRIPTION
**Pull request by lots0logs**
…in non-gnome environments.

### CODE REVIEW

**Comment by lots0logs** [comment]
RE: #113 @guinux  I know its still *rough around the edges* but let me know what you think.

**Comment by philmmanjaro** [comment]
@lots0logs: The work is just half done. Updater and all dialogs, like settings, still using no headerbar.

**Comment by philmmanjaro** [comment]
With this **AUR** is now always visible. This shouldn't be the case when **AUR** support is disabled (by default). Other than that the new look improves the visual so far.

**Comment by lots0logs** [comment]
@philmmanjaro Noted. I should have some more time to work on it tomorrow. Cheers!

**Comment by guinux** [comment]
Yes there's no need to comment code and use a notebook. You should only modify manager_window.ui file.

**Comment by lots0logs** [comment]
@guinux I used a notebook because its better UI for that area. The stack & switcher concept is fine for one-level but nesting them is not good for UI experience (IMO)

**Comment by guinux** [comment]
I used a notebook previously and some people didn't see the AUR tab. With a stackswitcher I think it's more visible.

**Comment by philmmanjaro** [comment]
@lots0logs: will check it when I'm home ...

**Comment by lots0logs** [comment]
K..Its still a WIP :wink:

**Comment by philmmanjaro** [comment]
@lots0logs: as of now I've a compiling issue with the latest patchset:
```
preferences_dialog.vala:60.3-60.34: warning: field `Pamac.PreferencesDialog.stack_switcher' never used
		Gtk.StackSwitcher stack_switcher;
		^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mirrors_config.vala:102.3-102.19: warning: method `Pamac.MirrorsConfig.write' never used
		public void write (HashTable<string,Variant> new_conf) {
		^^^^^^^^^^^^^^^^^
preferences_dialog.vala:60.3-60.34: error: could not find child `stack_switcher'
		Gtk.StackSwitcher stack_switcher;
		^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
preferences_dialog.vala:67.59-67.78: error: Cannot convert from `bool' to `int'
			Object (transient_for: transaction.application_window, use_header_bar: true);
```

**Comment by philmmanjaro** [comment]
With the release of **v4.0-beta4** this is now obsolete. Do you agree?

**Pull request closed without merging**
