### PR TITLE
Update de.po

### PR DESCRIPTION
**Pull request by raymontag**
"Erneuerungen" is not proper german for updates. "Aktualisierungen" is more natural.

### CODE REVIEW

**Comment by philmmanjaro** [comment]
We do it in transifex.

**Comment by raymontag** [comment]
Well, transifex is wrong on this. In Germany you say "Aktualisierungen" oder just "Updates". (Hint: I'm from Germany).

But it's your choice of course.

**Comment by philmmanjaro** [comment]
See e1ead00c6295ef9b5e14eecfafe4611832b6d244 and greetings from Munich :smile:

**Comment by killajoe** [comment]
@raymontag  what @philmmanjaro want to say is that translations are done there https://www.transifex.com with transilflex so corrections should be reported there, as far as i understand ;)

**Comment by philmmanjaro** [comment]
Seems I was to brief on this one. All translations we do in transifex and simply sync them. So any request to update translations on github will be closed with that given note.

**Comment by raymontag** [comment]
Ah, I see. Thanks for explanation :)

**Pull request closed without merging**
