### PR TITLE
Fix Issue 155

### PR DESCRIPTION
**Pull request by scachemaille**
My proposition to fix the issue #155 with OnlyCountry when user and root have different display language

### CODE REVIEW

**Comment by guinux** [comment]
Thanks, it works but please copy my syntax:
- use tab as indentation
- for condition use: if "space" (condiftion) "space" { "new_line" "tab" code; "new_line" }

**Comment by scachemaille** [comment]
like this?

**Comment by scachemaille** [comment]
like this?

**Comment by guinux** [comment]
perfect !

**Pull request merged**
