### PR TITLE
fix https://bugs.manjaro.org/index.php?do=details&task_id=14

### PR DESCRIPTION
**Pull request by oberon2007**
be polite and wait for ``mhwd-live`` script to finish installing?

### CODE REVIEW

**Comment by oberon2007** [comment]
Tested by editing the script in the chroot. I think 30s should be long enough for mhwd-live to finish?
Pamac is not in a hurry anyway. Maybe we can wait even longer just to be really safe...

**Comment by philmmanjaro** [comment]
Ok, seems my "[fix](https://github.com/manjaro/manjaro-tools/blob/stable-0.12.x/lib/util-iso-image.sh#L251)" never worked as the file was not even there yet.

**Comment by oberon2007** [comment]
I think it did until it got [removed](https://github.com/manjaro/manjaro-tools/commit/274c4f1707dda2c4a4498336a4adb5478f033ef7#diff-f2560f807d9955bca89d31b55cab67bfL252)
In any case, great, that @Kirek had the right pointer for us :smile: :+1:

**Comment by philmmanjaro** [comment]
Ok, makes sense now ...

**Pull request merged**
