### PR TITLE
Switch install reason

### PR DESCRIPTION
**Pull request by gaurapanasenko**
Now you can mark program as dependency and switch install reason from
menu

### CODE REVIEW

**Comment by philmmanjaro** [comment]
@guinux: is that any use or should we deny the request?

**Comment by gaurapanasenko** [comment]
At your choice. I made it to easily switching between automatic installed or installed as dependencies

**Comment by guinux** [comment]
Pamac can already switch install reason from "installed as dep" to "explicilty installed".
I enable it because it's not dangerous at all for the system. Enabling to switch from "explicitly installed" to "installed  as dep" is potentially dangerous if you don't know what you're doing so I'm not for it.

**Comment by philmmanjaro** [comment]
OK, NAK then :smile:

**Pull request closed without merging**
