### PR TITLE
Fix/systemd pamac-mirrorlist timer and service

### PR DESCRIPTION
**Pull request by kewlfft**
- This is adding `pacman -Syy` post command (see below). 
- Also adding randomized delay to avoid traffic at 0:00 from everybody. 
- Increasing the frequency to every 2 weeks should be reasonable as `-f5` is quick and the randomization ensure this is not concentrated at the same time.

>     It cannot be stressed enough, that every run of pacman-mirrors requires you to syncronize your database
>     $ sudo pacman -Syy
>     If you fail to do so, the issue/s which had you make change might not be solved. Furthermore you might run into partial-updated scenario which can cause havoc in your system.

### CODE REVIEW

**Comment by philmmanjaro** [comment]
@guinux: I don't think we need **pacman** here to sync the DBs. **Pamac** has a similar feature. Can you double-check this?

**Comment by kewlfft** [comment]
Thanks very much for the feedback, let me know if I misinterpreted and I will correct, randomization of the timer is also an improvement I propose

**Comment by guinux** [comment]
No pamac never auto force dba sync. So I will merge this. Thanks @kewlfft

**Comment by AladW** [comment]
...unattended partial upgrades in a new iteration? Marvelous.

**Comment by kewlfft** [comment]
@AladW this is changing server and then forcing a refresh of all package databases on the new server, anything wrong with it?

**Comment by AladW** [comment]
I don't get what you mean by "on the new server", since the service (and with that `pacman -Sy`) is run on the client, right? Again, not much of an issue on Manjaro but a world of hurt on Arch.

**Comment by kewlfft** [comment]
Sorry by changing server I meant changing to the closest Manjaro mirror. After changing mirror we force a refresh of the package database (on this closest mirror). The `pacman -Syy` is indeed run on the client. Is it clearer?

**Comment by AladW** [comment]
You're not in the danger of a partial upgrade because your mirrors were upgraded. Any potential changes in the mirror databases are only propagated to pacman (read: copied to `/var/lib/pacman/sync`) __after__ you've run `-Syy`. But since your local system is now inconsistent with the new databases, you've effectively done a partial upgrade.

https://bbs.archlinux.org/viewtopic.php?pid=1771159#p1771159

**Comment by kewlfft** [comment]
@AladW  Thanks for pointing this out, the [Manjaro wiki](https://wiki.manjaro.org/index.php?title=Pacman-mirrors#IMPORTANT) on the topic is therefore rather confusing. It is better to keep the old databases consistent with the system even after changing mirror then, and only use `-Syu`. If I understand correctly now, this step is a bit embarrassing and should be removed.

**Comment by kewlfft** [comment]
@AladW looking into it what you say make total sense and I can't explain the Manjaro wiki warning, @philmmanjaro @guinux before reverting this change, if you agree with Alad, what needs to be done first is correct the wiki otherwise someone else could, like me, want to implement again what is presented as an "important" note in the wiki. What is your view? Thanks all.

**Comment by philmmanjaro** [comment]
@kewlfft: In Manjaro it is recommended if you switch branches to do a -Syy first. Arch doesn't need that, as it doesn't use branches at all. Since this is focused software for Manjaro a revert is therefore not needed. Arch might do a revert on their packages. For Manjaro itself I don't see any steps to be taken.

**Comment by kewlfft** [comment]
@philmmanjaro 
We had some discussion on the forum and the recommended action is now `-Syyu` after using `pacman-mirrors` in order to avoid partial upgrades. The Manjaro wiki has been amended accordingly:
[forum - pacman-mirrors](https://forum.manjaro.org/t/pacman-mirrors-and-partial-upgrade-potential/41952)
[forum - wiki](https://forum.manjaro.org/t/wiki-pacman-mirrors-pacman-4-7-6-recommendations-for-maintenance-and-installation/41991)

I do understand `-Syy` is recommended after switching branch but still, without doing a full upgrade right away, the system state being inconsistent with the database isn't it a potential source of issue if this is followed by a package install  or an individual upgrade?
You obviously know this better than me and we may miss something that makes the full upgrade not necessary after the database local propagation, if you can let us know in this case.

**Comment by philmmanjaro** [comment]
Here we only want to sync with DBs, however don't upgrade the system. That is why we only use `-Syy` here.

**Comment by kewlfft** [comment]
@philmmanjaro: After this `-Syy`, if the user installs a package that has new libraries (before doing a full upgrade), do you confirm it won't break things? That was my concern.
(And obviously we won't launch a full upgrade here)

**Comment by AladW** [comment]
Easiest way out: put in the header that this tool should not be used with Arch under any circumstance, or at least, that doing so is unsupported both on the Arch end of things and Manjaro end of things.

**Comment by jonathonf** [comment]
This behaviour was [discussed as introducing partial upgrades](https://forum.manjaro.org/t/pacman-mirrors-and-partial-upgrade-potential/41952) on the forum with the result that the previous advice of `pacman -Syy` being replaced with `pacman -Syyu`.

Unless I've missed something, this change should be reverted.

**Comment by guinux** [comment]
Ok I removed `pacman -Syy` after updating mirrorlist (21b8e96).

**Pull request merged**
